// <auto-generated />
using Mano.Services.Coupan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mano.Services.Coupan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230819043000_seed_coupon_data")]
    partial class seed_coupon_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.7.23375.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mano.Services.Coupan.Model.Coupon", b =>
                {
                    b.Property<int>("CoupanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoupanId"));

                    b.Property<string>("CoupanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CoupanDisCount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CoupanId");

                    b.ToTable("coupans");

                    b.HasData(
                        new
                        {
                            CoupanId = 1,
                            CoupanCode = "1002",
                            CoupanDisCount = 12.0,
                            MinAmount = 3
                        },
                        new
                        {
                            CoupanId = 2,
                            CoupanCode = "1005",
                            CoupanDisCount = 50.0,
                            MinAmount = 10
                        },
                        new
                        {
                            CoupanId = 3,
                            CoupanCode = "1007",
                            CoupanDisCount = 30.0,
                            MinAmount = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
